CREATE SCHEMA IF NOT EXISTS `db_agile`;
USE `db_agile`;

DROP TABLE IF EXISTS ag_post;
CREATE TABLE IF NOT EXISTS ag_post (
	id INT PRIMARY KEY AUTO_INCREMENT,
	title VARCHAR(45) NOT NULL,
	author VARCHAR(45) NOT NULL,
	content TEXT NOT NULL,
	dateAdded DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	status TINYINT(1) NOT NULL DEFAULT 1
) engine = innoDB;

DROP TABLE IF EXISTS ag_comment;
CREATE TABLE IF NOT EXISTS ag_comment (
	id INT PRIMARY KEY AUTO_INCREMENT,
	post_id INT NOT NULL,
	author VARCHAR(45) NOT NULL,
	content TEXT NOT NULL,
	dateAdded DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	status TINYINT(1) NOT NULL DEFAULT 1,
	CONSTRAINT commentfk_1
		FOREIGN KEY (post_id)
		REFERENCES ag_post(id)
		ON UPDATE CASCADE
		ON DELETE CASCADE
) engine = innoDB;